# Generated by Django 5.1.1 on 2024-10-30 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_local', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
